### ISSUE TITLE
 User sentry_user_name does not have privileges for MSCK

### ISSUE THREAD

**Issue by ntallapa12** [lenchv/hive-driver#19]
We have sentry enabled (Active Directory based) kerberized cluster. And we are seeing this message occasionally and its not consistent. And this user "sentry_user_name" does have privileges for MSCK. We didnt see this issue while using JDBC and we are researching this issue as well, but mean while if you see anything suspicious in hive-driver please let us know

This is the full stack of the error:
User sentry_user_name does not have privileges for MSCK
 The required privileges: Server=server1->Db=database_name123->Table=table_name123->action=*;" error_code="40000" error_stack="*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException No valid privileges
 User sentry_user_name does not have privileges for MSCK
 The required privileges: Server=server1->Db=database_name123->Table=table_name123->action=*;:17:16
org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:400
org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:188
org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:267
org.apache.hive.service.cli.operation.Operation:run:Operation.java:337
org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:439
org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:405
org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:257
org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:501
org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1313
org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1298
org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39
org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39
org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingProcessor:process:HadoopThriftAuthBridge.java:705
org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286
java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149
java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624
java.lang.Thread:run:Thread.java:748
*org.apache.hadoop.hive.ql.parse.SemanticException:No valid privileges
 User sentry_user_name does not have privileges for MSCK
 The required privileges: Server=server1->Db=database_name123->Table=table_name123->action=*;:20:4
org.apache.sentry.binding.hive.HiveAuthzBindingHook:postAnalyze:HiveAuthzBindingHook.java:487
org.apache.hadoop.hive.ql.Driver:compile:Driver.java:497
org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1279
org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1266
org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:186
*org.apache.hadoop.hive.ql.metadata.AuthorizationException:User sentry_user_name does not have privileges for MSCK:22:2
org.apache.sentry.binding.hive.authz.HiveAuthzBinding:authorize:HiveAuthzBinding.java:343
org.apache.sentry.binding.hive.HiveAuthzBindingHook:authorizeWithHiveBindings:HiveAuthzBindingHook.java:687
org.apache.sentry.binding.hive.HiveAuthzBindingHook:postAnalyze:HiveAuthzBindingHook.java:472"

**Comment by lenchv** [comment]
I didn't face such errors before, but I looked a bit through the source code of [Hive](https://github.com/apache/hive) and I noticed that they call some hooks during the compilation of statements, probably the error happens in sentry handler, which is called by a hook. 

I didn't find the same error, but [his one](https://community.cloudera.com/t5/Support-Questions/quot-User-does-not-have-privileges-for-CREATETABLE-quot/td-p/21044) looks close to yours.

Have you looked at [this](https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/cm_sg_sentry_service.html) and [this](https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/sg_sentry_troubleshooting.html#general__view_current_permissions)?

Also, I don't think this is a problem with hive-driver and there is something can be done on the client side, but, please, let me know if you find a solution.

**Comment by lenchv** [comment]
And you can also look through the code of [sentry hook](https://github.com/apache/sentry/blob/master/sentry-binding/sentry-binding-hive/src/test/java/org/apache/sentry/binding/hive/TestHiveAuthzBindings.java). But I'm almost sure it is related to granted permissions

**Comment by ntallapa12** [comment]
Thanks for ruling out any issues from hive-driver side, will look into hive and sentry/AD configs, closing this issue for now.
