### ISSUE TITLE
Opening hiveSession on existing hiveClient hangs indefinitely when HS2 server is restarted

### ISSUE THREAD

**Issue by ntallapa12** [lenchv/hive-driver#20]
We are using hive-driver in REST API layer to connect to HS2 server and initiate some DDL commands. This is the way we have implemented it right now:
1. Initiate hiveClient when REST server is started (one time and singleton instance)
2. Open one hiveSession per request and 1-many hiveOperations as required and close them at the end of every REST API call.

In some instances, when the REST server is running if the underlying HiveServer2 is restarted on the hadoop cluster, then opening hiveSession on existing hiveClient (which is created before HS2 restart), is hanging indefinitely with no errors.

Few questions in this context:
Is it possible for hive-driver to return whats has happened and why it hanged (better exception handling in this scenario)?
Do we have to restart REST API server when HS2 server is restarted?
Is there a way to refresh/recreate hiveClient based on some configuration?

**Comment by lenchv** [comment]
Some errors, particularly of the connection one, are asynchronous, so it is difficult to track them and throw an exception in the appropriate way and time. You may try to subscribe on client 'error' event:

```
const client = new hive.HiveClient(
    TCLIService,
    TCLIService_types
);
client.on('error', (error) => {
     // do re-connect
});
```

Also, try to use connection [options](https://github.com/lenchv/hive-driver/blob/master/lib/connection/contracts/IConnectionOptions.ts#L7):

```
    max_attempts?: number,
    retry_max_delay?: number,
    connect_timeout?: number,
    timeout?: number,
```

These options are passed directly to thrift connection. For more details about these options, you can look at `node_modules/hive-driver/node_modules/thrift/lib/nodejs/lib/thrift/http_connection.js` or `node_modules/hive-driver/node_modules/thrift/lib/nodejs/lib/thrift/connection.js` depends on what kind of connection you use.

Let me know if it helps.

Also, can you tell me what connection you use binary or HTTP? Probably, I can dig deeper to find some workaround for such cases.

**Comment by ntallapa12** [comment]
I am using these options to make the connection 
            new hive.connections.TcpConnection(),
            new hive.auth.PlainTcpAuthentication({
                username: username,
                password: password,
            }))

Is there any documentation on above params that you know of? esp connect_timeout and timeout. I hope the unit is millis.

This is what I tried: I started rest server, went ahead to stop HS2 server and didnt receive any event on subscribe (client.on) and also when getting hiveSession on existing hiveClient, it hung.
Looks like I have to create new hiveClient for every request, do you know how much resource/time intensive it is to create hiveClient for every new REST API request as opposed to what I was doing earlier (like hiveClient only one and create as many sessions as many requests)

**Comment by lenchv** [comment]
@ntallapa12 actually I did not find any documentation for [thrift](https://www.npmjs.com/package/thrift) module in node js, I found out about these options from source code. And yes, it seems like values in mills.

I tried to reproduce the behavior you described, and I see what you mean. It seems like those options not really helpful. I noticed that thrift connection has a few additional events: close, timeout, reconnecting (the last is called when you define those options above). 

Also, I added logic, which will throw an exception when a session is opened but a connection is lost. It led to hanging.

I added to [troubleshooting.md](https://github.com/lenchv/hive-driver/blob/b45826598496dc1c1557b8674a4fbf2f3f1a8a6e/docs/troubleshooting.md#lost-connection) an explanation of how to re-connect in case the connection is lost. You will be able to try this approach as soon as I publish 0.1.3 version.

Also, below is a rough example of how it can be used.
For this example you can run a test server:

```bash
git clone https://github.com/lenchv/hive-driver.git
cd hive-driver/.docker
make up TYPE=tcp.ldap

# to stop server
docker-compose stop

# to start again
docker-compose start
 
# to shutdown
make down
```

hive.js
```javascript

const hive = require('hive-driver');
const { TCLIService, TCLIService_types } = hive.thrift;
const { HiveClient, auth, connections } = hive;

const connection = new connections.TcpConnection();
const authProvider = new auth.PlainTcpAuthentication({
    username: 'admin',
    password: '123456'
});

const client = new HiveClient(
    TCLIService,
    TCLIService_types
);

const utils = new hive.HiveUtils(
    TCLIService_types
);

client.on('error', (error) => {
	console.error('[Hive Error]', error);
});

client.on('reconnecting', (params) => {
	console.error('[Hive Reconnecting]', params);
});

client.on('close', () => {
	console.error('[Hive Connection Closed]');
	connect(30).catch(error => {
		console.error('[Hive Connection Failed]', error);
	});
});

const connect = (attempts) => new Promise((resolve, reject) => {
	setTimeout(() => {
		client.connect({
			host: '127.0.0.1',
			port: 10000,
			options: {}
		}, connection, authProvider).then((client) => {
			console.log('Connected successfully!');
			resolve(client);
		}, (error) => {
			console.error('[Hive Connection Failed]: ' + attempts, error);

			if (!attempts) {
				reject(error);
			} else {
				connect(attempts - 1).then(resolve, reject);
			}
		});
	}, 3000);
});

module.exports = connect(30).then(async client => {
	await migration(client);

	return hiveService(client);
}, (error) => {
	console.error('[Hive Connection Failed]', error);
});

function migration(client) {
    return client.openSession({
        client_protocol: TCLIService_types.TProtocolVersion.HIVE_CLI_SERVICE_PROTOCOL_V10
    }).then(async (session) => {
		const createTableOperation = await session.executeStatement(
			'CREATE TABLE IF NOT EXISTS pokes (foo INT, bar STRING)'
		);
		await utils.waitUntilReady(createTableOperation, false, () => {});
		await createTableOperation.close();
        
        return await session.close();
    })
}

function hiveService(client) {
	return {
		openSession() {
			return client.openSession({
				client_protocol: hive.thrift.TCLIService_types.TProtocolVersion.HIVE_CLI_SERVICE_PROTOCOL_V10
			});
		},

		async insertIntoPokes(session, data) {
			const operation = await session.executeStatement(
				`INSERT INTO pokes (foo, bar) VALUES (${data.foo}, '${data.bar}')`
			);
			await utils.waitUntilReady(operation, false, () => {});
			await operation.close();
		},

		async selectFromPokes(session) {
			const operation = await session.executeStatement(
				`SELECT * FROM pokes`, { runAsync: true }
			);
			await utils.waitUntilReady(operation, false, () => {});
			await utils.fetchAll(operation);
			await operation.close();

			return utils.getResult(operation).getValue();
		}
	};
};
```

server.js
```javascript
const express = require('express');
const app = express();
const bodyParser = require("body-parser");
const port = 3000;

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

require('./hive').then((hiveService) => {
	app.post('/', async (req, res, next) => {
		try {
			const session = await hiveService.openSession();
			
			await hiveService.insertIntoPokes(session, req.body);
			await session.close();
	
			res.json({ "success": true });
		} catch (error) {
			next(error);
		}
	});
	
	app.get('/', async (req, res, next) => {
		try {
			const session = await hiveService.openSession();

			const result = await hiveService.selectFromPokes(session)
			await session.close();

			res.json(result);
		} catch (error) {
			next(error);
		}
	});

	app.use(function (err, req, res, next) {
		console.error(err.stack)
		res.status(500).send('Something broken!')
	});
});

app.listen(port, () => console.log(`Example app listening on port ${port}!`));
```

**Comment by ntallapa12** [comment]
this is working like a charm. thank you
