### ISSUE TITLE
Need additional details on the created client connections

### ISSUE THREAD

**Issue by ntallapa12** [lenchv/hive-driver#25]
I am using client API to create connection. For debugging purposes I am looking for details on the created connections using this driver.

Just like I am tracking created sessions via 
const sessionId = session.sessionHandle.sessionId.guid.toString('hex');

I also need to track or looking for some way to track my opened/closed connections in case I have to debug any issues going further.

Please let me know if you have any inputs on this.

**Comment by lenchv** [comment]
Hi @ntallapa12 , actually, there is no tagging logic on creation connections. But you can implement some workaround, something like this:

```javascript
const uuid = require('uuid');

class TaggedTcpConnection extends hive.connections.TcpConnection {
	tag = null

	connect(...args) {
		this.tag = uuid.v4();

		return super.connect(...args);
	}
}

// ...

client.connect(
    {
        host: 'localhost',
        port: 10000
    },
    new TaggedTcpConnection(),
    new hive.auth.NoSaslAuthentication()
).then(() => {
	console.log(client.connection.tag);
});

client.on('close', () => {
	console.log(client.connection.tag);
});
```

**Comment by ntallapa12** [comment]
Not really a tagged connection from client side rather I was looking for some kind of unique connection id so. that if sth goes wrong on client I can look into hiveserver2 logs
