### ISSUE TITLE
Connection to Hive via Zookeeper

### ISSUE THREAD

**Issue by danielamigos** [lenchv/hive-driver#35]
Hi! I'm trying to connect to hive through zookeeper.  The connection string I use to connect within beeline to hive is this:

jdbc:hive2://hpchdp2-zk-1.hpc.server.com:2181,hpchdp2-zk-2.hpc.server.com:2181,hpchdp2-zk-3.hpc.server.com:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2-ranger

Is there a way I can specify these properties (multiple servers, serviceDiscoveryMode or zooKeeperNamespace) or this type of connection string via this hive driver?

**Comment by lenchv** [comment]
Hi @danielamigos ! The short answer is there are no possibilities for this. As a solution you can try using knox gateway:

https://docs.cloudera.com/HDPDocuments/HDP3/HDP-3.1.5/configuring-proxy-knox/content/ha_configure_knox_for_ha.html

Or if you can provide test environment with zookeeper I can check whether it is possible to connect at all. The examples of testing environments you can find here: https://github.com/lenchv/hive-driver/tree/master/.docker

Also, here is an interesting library, that can communicate with zookeeper. Probably, with this lib, you can retrieve connection data that can be used via the hive-driver:

https://www.npmjs.com/package/thrift-zookeeper-client

**Comment by lenchv** [comment]
Hi @danielamigos! I added an instruction how to connect to hive if you use zookeeper. Here is a link: [/docs/connections.md#zookeeper](https://github.com/lenchv/hive-driver/blob/master/docs/connections.md#zookeeper)
