### ISSUE TITLE
Fetching massive resultset occurs heap OOM

### ISSUE THREAD

**Issue by chancethecoder** [lenchv/hive-driver#36]
Hi, lenchv.

Here is my situation:
- nodejs server killed by [heap OOM](https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory) after some hive query which returns massive resultset
- i used `hiveUtils.fetchAll` and noticed that it occurs OOM
- tried to iterate fetch - some process - flush loop

my iteration code is like this:

```javascript
while (operation.hasMoreRows()) {
    await operation.fetch();
    const rows = hiveUtils.getResult(operation).getValue();
    // some process here

    operation.data = []; // flush
}
```

It works, but i think `operation.data` is a private field and not supposed to be flushed this way.

do you have any idea to do this better way? (or is it ok?)

**Comment by lenchv** [comment]
Hi @chancethecoder ! Great catch. It worth adding `flush()` to clean `data`. But for now it is good solution to clear it on the instance, as long as it solves the issue. I'll make an update and let you know!

**Comment by lenchv** [comment]
I added the method `flush()` and released a new version
