### ISSUE TITLE
Unable to get Query Result. Code failing with below error log.

### ISSUE THREAD

**Issue by aashumundrawinzo** [lenchv/hive-driver#39]
failed with error *org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.tez.TezTask:28:27
org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380
org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:257
org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:293
org.apache.hive.service.cli.operation.Operation:run:Operation.java:320
org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530
org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506
sun.reflect.GeneratedMethodAccessor107:invoke::-1
sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43
java.lang.reflect.Method:invoke:Method.java:498
org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78
org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36
org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63
java.security.AccessController:doPrivileged:AccessController.java:-2
javax.security.auth.Subject:doAs:Subject.java:422
org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1844
org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59
com.sun.proxy.$Proxy37:executeStatement::-1
org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280
org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531
org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437
org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422
org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39
org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39
org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56
org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286
java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149
java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624
java.lang.Thread:run:Thread.java:748

**Comment by lenchvolodymyr** [comment]
Hello @aashumundrawinzo ! Could you provide more information?

What statement are you trying to execute? Does it work via beeline? What is a version of your hive server? Could you send a code example that leads to this error?

It is a strack trace from the server, so it is difficult to troubleshoot without knowing this information.

**Comment by aashumundrawinzo** [comment]
Hello @lenchvolodymyr . This issue has been solved. We solved it by restarting our hive server. Many thanks for your help.
