### ISSUE TITLE
possible typo on NoSaslAuthentication

### ISSUE THREAD

**Issue by davidkhala** [lenchv/hive-driver#49]
In the example I see a line of 
```
...
new hive.auth.NoSaslAuthentication() 
...
```
Should it be `NoSslAuthentication`?

**Comment by lenchv** [comment]
Hi @davidkhala , no, it's correct, SASL is [Simple Authentication Security Layer](https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer) and it works accordingly with Hive [specification](https://cwiki.apache.org/confluence/display/hive/setting+up+hiveserver2)
