### ISSUE TITLE
hive PlainTcpAuthentication throwing read ECONNRESET

### ISSUE THREAD

**Issue by andyFang94** [lenchv/hive-driver#52]
When I try to test connecting to the hive database,  hive.auth.PlainTcpAuthentication

Have you ever encountered such an error? 

read ECONNRESET

When I link to the Hive database to query data, I occasionally get an error

@drzippie @khwj @lenchv @lenchvolodymyr

**Comment by lenchv** [comment]
Hi @andyFang94 this error relates to the network connection to the database, you should check whether it is stable
