### ISSUE TITLE
StatusError is thrown when `util.fetchAll` with Impala

### ISSUE THREAD

**Issue by 5d-jh** [lenchv/hive-driver#53]
With connected to Impala, `StatusError: Restarting of fetch requires enabling of query result caching.` is thrown when do `HiveUtils#fetchAll`.

I discovered that, based on impyla library, in HiveOperation.ts line 67, replacing firstFetch with nextFetch resolves the issue.

This issue could be related with fetch orientation, but I couldn't find any specific relevant documentation.

**Comment by 5d-jh** [comment]
https://github.com/cloudera/impyla/blob/b8272c61dd9023019b65666b923469639edb3818/impala/hiveserver2.py#L1381

Here's Impyla's relevant fetch method.

**Comment by lenchv** [comment]
Hi @5d-jh I suppose I can add parameter to "fetch()", and remain fetch first to keep backward compatibility, smth like this:

```
enum FetchOrientation { FETCH_FIRST, FETCH_NEXT }

fetch(orientation: FetchOrientation = FetchOrientation.FETCH_FIRST) {
  // ...
  if (orientation === FetchOrientation.FETCH_NEXT) {
    this.fetchNext()
  } else {
    this.fetchFirst();
  }
}
```

and pass the parameter through HiveUtils.fetchAll as well, does it work for you?

**Comment by 5d-jh** [comment]
Yes, that would work for me
