### ISSUE TITLE
OperationStateError is thrown when state is pending

### ISSUE THREAD

**Issue by 5d-jh** [lenchv/hive-driver#54]
In `waitUntilReady` method, if received state is pending, OperationStateError is thrown. I wonder if it's intended behavior.

I have no issues without throwing error(replaced with`return false`).

```
@@ -97,7 +97,7 @@ WaitUntilReady.js
-   throw new OperationStateError_1.default('The operation is in a pending state', response);
+   return false;
```

I connected with Impala instead of Hive.

**Comment by lenchv** [comment]
Hi @5d-jh , yes, you're right, it makes sense to return false in case of pending state, feel free to send PR, otherwise I'll be able to fix the issue later this week

**Comment by 5d-jh** [comment]
I will leave a PR right away. Thanks for checking out 🙂
