### ISSUE TITLE
return code 1 from org.apache.hadoop.hive.ql.exec.StatsTask

### ISSUE THREAD

**Issue by xunziheng** [lenchv/hive-driver#60]
Hi @lenchv ,
I met a issue when I use like this:
```
sql = `INESRT INTO mytable VALUES (...)`;
await this.connect();
const { session, utils } = this;
const createTableOpertion = await session.executeStatement(sql, { runAsync: false });
await utils.waitUntilReady(createTableOpertion); // errror point
await createTableOpertion.close();
```
ERROR: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.StatsTask;

insert sql is correct I confirmed.

any ideas? or need more debug info.

regards.

**Comment by xunziheng** [comment]
all work well if I use dbeaver connection to excute same sql.

**Comment by lenchv** [comment]
Hello @xunziheng ,
What version Hive and Hadoop do you use?
Could you provide the DDL of the table "mytable" (CREATE statement)? The column names can be changed if they contain sensative info

Also, can you check Hive logs? looks like the error comes from the server

**Comment by xunziheng** [comment]
Hello @lenchv ,
sorry for lately reply, It works, but I don't know exactly why. I just turned off this configuration in hive-site.xml.

![image](https://github.com/lenchv/hive-driver/assets/35691153/1a19c60e-d303-4ef8-8bcf-cd396d6c6935)

I guess it's time-out to connect thrift api.
