### ISSUE TITLE
Method flush is missing in interface IOperation

### ISSUE THREAD

**Issue by AKy3HELljOB** [lenchv/hive-driver#61]
Method 'flush' is implemented in class 'HiveOperation', but not in interface 'IOperation'. I need this method to read in a stream.

**Comment by lenchv** [comment]
Hi @AKy3HELljOB ! Feel free to create a PR with the change you need and I release a new version. Otherwise, you'll need to wait until it's implemented

**Comment by AKy3HELljOB** [comment]
PR with https://github.com/lenchv/hive-driver/pull/62/files

**Comment by lenchv** [comment]
deployed version 0.3.1
