### ISSUE TITLE
connect hive

### ISSUE THREAD

**Issue by PetiteBoy** [lenchv/hive-driver#63]
i can not connect hive,
when i openSession it is not back any things

**Comment by lenchv** [comment]
Hi @PetiteBoy ! I need more context to help you find a cause. Can you send a piece of code how you're trying to connect and hive-site.xml for the hive server?

**Comment by MiXiaoLuo** [comment]
您好，连接hive后无报错，session无内容。
const hive = require('hive-driver');
const { TCLIService, TCLIService_types } = hive.thrift;
const client = new hive.HiveClient(
    TCLIService,
    TCLIService_types
);

function text(){
  try {
    client.connect(
      {
          host: '192.168.1.1',
          port: 10000,
          options:{
            username:'admin',
            password:'123456'
          }
      },
      new hive.connections.TcpConnection(),
      new hive.auth.NoSaslAuthentication()
    ).then(async client => {
    
      const session = await client.openSession({
          client_protocol: TCLIService_types.TProtocolVersion.HIVE_CLI_SERVICE_PROTOCOL_V10
      });
      console.log(session); //无打印
      const response = await session.getInfo(
          TCLIService_types.TGetInfoType.CLI_DBMS_VER
      );
    
      console.log(response.getValue());
    
      await session.close();
    }).catch(error => {
      console.log(error);
    });
  } catch (error) {
    console.log(error)
  }
}
text();

**Comment by ArunKarthick-pss** [comment]
@PetiteBoy you got a solution for session establishing issue??
